// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDT23p3KDd3pQf13UiQOuIjmemyBlMYPBg',
    appId: '1:876968672828:web:37fa076850a25b10044d39',
    messagingSenderId: '876968672828',
    projectId: 'softielwebsite',
    authDomain: 'softielwebsite.firebaseapp.com',
    databaseURL: 'https://softielwebsite-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'softielwebsite.firebasestorage.app',
    measurementId: 'G-YC1GH5KDCB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7betzMbk3m5ToNEd1miF80DKtT0woytc',
    appId: '1:876968672828:android:b10069d2479b16b1044d39',
    messagingSenderId: '876968672828',
    projectId: 'softielwebsite',
    databaseURL: 'https://softielwebsite-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'softielwebsite.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC790CLNNtDrM7rbz6TRDBRN277g_2_4yI',
    appId: '1:876968672828:ios:edefee2eb8134a7c044d39',
    messagingSenderId: '876968672828',
    projectId: 'softielwebsite',
    databaseURL: 'https://softielwebsite-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'softielwebsite.firebasestorage.app',
    iosBundleId: 'com.softiel.softielClientHub',
  );
}
